### ISSUE TITLE
Images with high memory size not loading

### ISSUE THREAD

**Issue by sandeshgb** [sarriaroman/photoviewer#108]
I'm having images whose sizes range between 1.5 Mb - 2.5 Mb. Such images doesnot open and an error message occurs "Error loading image"

Version used: 1.1.11

**Comment by leventozkann** [comment]
Same issue in android devices.

**Comment by sarriaroman** [comment]
Must be solved in version 1.1.13.

**Comment by sandeshgb** [comment]
Installed the above mentioned version,image doesn't open and it force stops the app.

Also tried v1.1.15, but no help.

**Comment by aliosmanyuksel** [comment]
@sandeshgb i have got this issue. Anyone help me?

**Comment by sandeshgb** [comment]
@sarriaroman @aliosmanyuksel 
Any progress regarding this issue...!!

**Comment by sarriaroman** [comment]
This must be solved on version 1.1.16
