### ISSUE TITLE
Stuck loading image after 1.1.15 {android}

### ISSUE THREAD

**Issue by julianCast** [sarriaroman/photoviewer#109]
I have android 7.0.1 and after the last update, the plugin wont work, if the image is base64 its get stuck on loading, if image is a url http, quit the app.

**No problem in plugin version 1.1.11**

 ionic (Ionic CLI) : 3.19.1
cordova (Cordova CLI) : 7.1.0    
@ ionic/app-scripts : 3.1.0
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

```
this.imageData = 'data:image/jpeg;base64,' + r.image_data;
const viewer = new PhotoViewer();
viewer.show(this.imageData, '', {share:false})
```

![20180213_122018](https://user-images.githubusercontent.com/559677/36147395-54fe4118-10b8-11e8-8be2-ec9c9c2cb908.png)

**Comment by fermedina** [comment]
+1

**Comment by julianCast** [comment]
NO PROBLEM in 1.1.11, so it is an error on the 1.1.15

**Comment by sandeshgb** [comment]
@julianCast but does this version of plugin open images with size greater than 2MB

**Comment by julianCast** [comment]
@sandeshgb Sorry I haven't tried with those sizes.

**Comment by sarriaroman** [comment]
This must be solved with 1.1.16. Sorry about the problems.

**Comment by julianCast** [comment]
Solved! Thank you for your work.

**Comment by sylvainb31** [comment]
Hi adrenaline15, have you fond a solution for your problem when re-adding the plugin ? 
I have the same error ...
