### ISSUE TITLE
Plugin crashes app on Android8

### ISSUE THREAD

**Issue by karimwarp** [sarriaroman/photoviewer#127]
here is my info
cli packages: (C:\Users\karim\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.9.4
    npm  : 5.6.0
    OS   : Windows 10

and i use this code to view image

viewImage(image: any) {
    this.photoViewer.show(image.ImageUrl3x,image.Name,{share:true});
  }
it works fine on phones/devices with android 7 and below but on Android 8 it says AppName crashed, reopen AppName

**Comment by sarriaroman** [comment]
Solved with https://github.com/sarriaroman/photoviewer/pull/125
