### ISSUE TITLE
iOS Crash on Version 1.1.17

### ISSUE THREAD

**Issue by LeoCreer** [sarriaroman/photoviewer#130]
iOS Crash on photoviewer Version 1.1.17

tested on ios 11.3 and 11.4 on iPhone X, 8 and 5s

Rolled it back to 1.1.16 and it everything started to work again.

**Comment by erikramalho** [comment]
Confirmed that 1.1.16 works fine.

**Comment by writer0713** [comment]
@LeoCreer notice #129 . 1.1.17 author will fix it asap. 
for others who will see this issue, let me explain details.

1.1.16 : ios no problem. android share crashes.
1.1.17 : android share no problem(fixed). ios crashes with options (no options, no problem).

currently, @almas (who made 1.1.17) is checking it.

**Comment by almas** [comment]
I just fixed and created pull request. 
https://github.com/sarriaroman/photoviewer/pull/131
:) 👍

**Comment by sarriaroman** [comment]
Closed with 1.1.8. Thanks to @almas
