### ISSUE TITLE
Android : Black Screen

### ISSUE THREAD

**Issue by VivekanandanS** [sarriaroman/photoviewer#147]
I have passed base64 image to preview it . Nothing happed , a black screen and spinner is showing up

**Comment by marioluquem** [comment]
Hi, did you solve it? I have the same problem

**Comment by julianCast** [comment]
Im facing the same problem, on last version 1.1.18 with android and iOS

**Comment by charlesCaballero** [comment]
Any update about this please.... i have the same problem..

**Comment by sarriaroman** [comment]
You must use version 1.1.22 to solve the issue or enable share in previous versions.
