### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by ThatoMokhomong** [sarriaroman/photoviewer#15]
-pre-compile:

-compile:
    [javac] Compiling 13 source files to /project/bin/classes
    [javac] /project/src/com/sarriaroman/PhotoViewer/PhotoActivity.java:3: error: package uk.co.senab.photoview does not exist
    [javac] import uk.co.senab.photoview.PhotoViewAttacher;
    [javac]                             ^
    [javac] /project/src/com/sarriaroman/PhotoViewer/PhotoActivity.java:19: error: package com.squareup.picasso does not exist
    [javac] import com.squareup.picasso.Picasso;
    [javac]                            ^
    [javac] /project/src/com/sarriaroman/PhotoViewer/PhotoActivity.java:26: error: cannot find symbol
    [javac] 	private PhotoViewAttacher mAttacher;
    [javac] 	        ^
    [javac]   symbol:   class PhotoViewAttacher
    [javac]   location: class PhotoActivity
    [javac] /project/src/com/sarriaroman/PhotoViewer/PhotoActivity.java:94: error: cannot find symbol
    [javac] 		mAttacher = new PhotoViewAttacher(photo);
    [javac] 		                ^
    [javac]   symbol:   class PhotoViewAttacher
    [javac]   location: class PhotoActivity
    [javac] /project/src/com/sarriaroman/PhotoViewer/PhotoActivity.java:127: error: package com.squareup.picasso does not exist
    [javac] 				.into(photo, new com.squareup.picasso.Callback() {
    [javac] 				                                     ^
    [javac] /project/src/com/sarriaroman/PhotoViewer/PhotoActivity.java:125: error: cannot find symbol
    [javac] 		Picasso.with(this)
    [javac] 		^
    [javac]   symbol:   variable Picasso
    [javac]   location: class PhotoActivity
    [javac] Note: /project/src/org/apache/cordova/splashscreen/SplashScreen.java uses or overrides a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] 6 errors

BUILD FAILED
/android-sdk/tools/ant/build.xml:716: The following error occurred while executing this line:
/android-sdk/tools/ant/build.xml:730: Compile failed; see the compiler error output for details.

**Comment by sarriaroman** [comment]
For some reason maven is not able to download the Picasso library. Try to open the project into Android Studio and wait until AS download the library from the repository.
