### ISSUE TITLE
Close button visibility for iOS

### ISSUE THREAD

**Issue by Sumit343** [sarriaroman/photoviewer#150]
Close button is not clearly visible on iOS devices if button surrounding is white.

**Comment by cabaird** [comment]
We are seeing this issue as well.

**Comment by CesarDublasSop** [comment]
This would be reaaly usefull. Has anybody found a workarround or a way to apply some background color?

**Comment by cabaird** [comment]
We ended up finding a javascript plugin that did what we needed, removing the need for native implementation in a cordova plugin.  
https://github.com/s-yadav/ImageViewer

**Comment by Hanisch-IT** [comment]
Is there any solution or just a closed issue?

**Comment by Sumit343** [comment]
There is a temporary solution, in iOS build move to **Plugins -> PhotoViewer.m** then replace line number 202 and 203 with : 
202 -> [closeBtn setFrame:CGRectMake(0, viewHeight - 50, viewWidth, 50)]; (Fit button width)
203 -> [closeBtn setBackgroundColor:[UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:0.6]]; (Button background color/shadow)

**Comment by sarriaroman** [comment]
Nice solution, please create a PR @Sumit343 :)
