### ISSUE TITLE
Only works on emulator not on my Device

### ISSUE THREAD

**Issue by danielOnTree** [sarriaroman/photoviewer#151]
iam almost done with this crap....each version has to be compatible with anothere one, and there are no explaination, just small pieces of ****...

Can someone explain why i cant use this "easy" usage, so it can work on both....the emulator AND my DEVICE....

I have and samsung s5...is there an secret "do_It" Button on the debug-settings that no one has already posted yet?

I get no errors, no nothing....i have just my button which i can use PhotoViewer with the emulator but not with the Device...so its not the Code......

**Comment by sarriaroman** [comment]
Issues related with permissions on Android were solved using "share" in true or with the latest version (1.1.22).
