### ISSUE TITLE
Property 'provide' is missing in type 'PhotoViewerOriginal'

### ISSUE THREAD

**Issue by dotbenj** [sarriaroman/photoviewer#156]
I have an error when I'm trying to add this plugin to my project.
`Property 'provide' is missing in type 'PhotoViewerOriginal'` This is the error I have on the console when I'm trying to emulate my app.
On the app I have an error like `Invalid provider for the NgModule 'App Module'`

It seem like angular don't recognize PhotoViewer as a valid Provider

I'm on Ionic 3 Angular 5

**Comment by FabianTe** [comment]
Happend for me too but with Ionic 4.

**Comment by bipoza** [comment]
I fix it installing uninstalling ionic native 5 photo-viewer and installing 4 version
```
$ npm uninstall @ionic-native/photo-viewer
$ npm i @ionic-native/photo-viewer@4.20.0
```

**Comment by austinhutchison** [comment]
@bipoza thank you this is exactly what I needed to get Photo Viewer working on Ionic 3.9.2

**Comment by thameurr** [comment]
after the release of ionic 4 any native plugin used in ionic 3 you must add @4 in the end of each command like that `npm i @ionic-native/photo-viewer@4`
