### ISSUE TITLE
photo viewer working in ionic 4?

### ISSUE THREAD

**Issue by selvam326** [sarriaroman/photoviewer#157]
Hi,

It is working with ionic 4 photo viewer?

**Comment by iNiravJoshi** [comment]
I am also Facing same error in ionic 4.

**Comment by lim-enhui** [comment]
https://forum.ionicframework.com/t/ionic-4-photo-viewer-compilation-error/155201

**Comment by lim-enhui** [comment]
fixed using stable version from 1.1.18

**Comment by iNiravJoshi** [comment]
Thanks for prompt reply.

**Comment by sarriaroman** [comment]
Fixed on version 1.2.1. You can now use the new features too :)
