### ISSUE TITLE
Ionic app crashes on iOS - [NSNull length]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by sjregan** [sarriaroman/photoviewer#158]
When I attempt to load a picture with:

```
this.photoViewer.show(item.featureImageUrl.full, '', {
            share: true,
            closeButton: true,
            copyToReference: true,
            headers: ''
})
```

the app crashes with:

```
[NSNull length]: unrecognized selector sent to instance
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull length]: unrecognized selector sent to instance 
```

Debugger is at line 270 of PhotoViewer.m:

```if (headerString == nil || [headerString length] == 0) {```

in function:

```- (NSDictionary *)headers:(NSString *)headerString {```

The value of headerString is (NSNull *)

**Platform**: iOS 12.1.2

**Comment by sjregan** [comment]
Figured the problem, I needed to add the following line to config.xml:

```<allow-navigation href="about:blank" />```

**Comment by aacassandra** [comment]
Hi @sjregan , what do ou know , how add this on capacitor?
