### ISSUE TITLE
iOS: Error with firebase URL

### ISSUE THREAD

**Issue by TdoubleG** [sarriaroman/photoviewer#184]
Hey there,

the plugin can't show firebase URLs in iOS. In Android it works like intended.
Does anybody have a solution for this?

That is my code:
```
  public showImage(url: string): void {
    if (this.platform.is('ios')) {
      url = decodeURIComponent(url);
    }

    this.photoViewer.show(url);
  }
```

**Comment by QuantariusRay** [comment]
@sarriaroman ^^^

**Comment by parodenas** [comment]
Hi, @TdoubleG did you find a solution?

**Comment by TdoubleG** [comment]
@QuantariusRay  @parodenas 
I forked this one and fixed the bug for firebase URLs

https://github.com/TdoubleG/photoviewer

Have fun :)

**Comment by parodenas** [comment]
@TdoubleG is working, thank you! :D

**Comment by jcgz100** [comment]
@TdoubleG  thanks for this !. I was stuck in this for days. 

Thank you

**Comment by thameurr** [comment]
not working : 
`The file to show is not a valid image or could not be loaded `

**Comment by TdoubleG** [comment]
@thameurr what kind of url do you have?

**Comment by thameurr** [comment]
@TdoubleG  firebase storage link

**Comment by TdoubleG** [comment]
@thameurr and you are using the package from here: https://github.com/TdoubleG/photoviewer

Do like this:
```
ionic cordova plugin rm com-sarriaroman-photoviewer
ionic cordova plugin add https://github.com/TdoubleG/photoviewer
```

**Comment by thameurr** [comment]
same problem

**Comment by ahmadwa** [comment]
@TdoubleG thanks, I do it as you wrote. every thing is working.
for iOS use:
`if (this.functions.isIos) {
      // src = decodeURIComponent(src);
      this.photoViewer.show(src);
    } else {
      this.photoViewer.show(src, '', options);
    }`

**Comment by alaswer** [comment]
> @QuantariusRay @parodenas
> I forked this one and fixed the bug for firebase URLs
> 
> https://github.com/TdoubleG/photoviewer
> 
> Just use it like this:
> 
> ```
>  public showImage(url: string): void {
>     this.photoViewer.show(url);
>   }
> ```
> 
> Have fun :)

Thank you so much!
