### ISSUE TITLE
Any way to save opened image locally?

### ISSUE THREAD

**Issue by sorxrob** [sarriaroman/photoviewer#196]
Hello, nice library!

Is there a way to add a button so we can save the image locally?

Thanks!

**Comment by miljosh68** [comment]
+1 

I was also searching for the exact same thing. I wish to show images in my 'assets/img/' folder.

**Comment by sorxrob** [comment]
Nevermind. 

For ionic users.

1. Create a modal with black toolbar and background
2. Add save icon on the right part of the toolbar
3. Position the image in the center of the modal (use flex)
4. Use https://ionicframework.com/docs/native/photo-library to save image
