### ISSUE TITLE
Using Cocoapods for iOS breaks Cordova CLI tools

### ISSUE THREAD

**Issue by jfrumar** [sarriaroman/photoviewer#2]
Since the iOS source requires the use of Cocoapods, the Cordova CLI tool cannot compile:

`ld: library not found for -lPods-AFNetworking
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

As a result I have to fork this project and strip out the iOS code.

**Comment by sarriaroman** [comment]
Yes, I'm working to solve this dependency. I will update it as soon as I have a working solution.

**Comment by sarriaroman** [comment]
Can you try to install pods in this way: "pod install --no-integrate"? Maybe that's a simpler solution.

**Comment by sarriaroman** [comment]
CocoaPod dependency was removed. This issue is now closed.
