### ISSUE TITLE
1.3.0

### ISSUE THREAD

**Issue by Aviho-M** [sarriaroman/photoviewer#229]
why u not set 1.3.0 v to public. @sarriaroman 
version 1.25.0 always have crash at android

**Comment by gabripianzi** [comment]
any update on the 1.3.0 version? the version is still not available via npm.
Thanks

**Comment by raulnoz** [comment]
Please upload 1.3.0 to npmjs

**Comment by sarriaroman** [comment]
Published to npm https://www.npmjs.com/package/com-sarriaroman-photoviewer
