### ISSUE TITLE
consider support "data:image/png;base64" 

### ISSUE THREAD

**Issue by pengVc** [sarriaroman/photoviewer#23]
if so, it's another good way for presenting image faster.

**Comment by NorthMcCormick** [comment]
Base64 images do work, testing on iOS 9 and iPhone6s+ right now, not sure about android

**Comment by Oliv** [comment]
Hello there, 
I just tried to use base64 in android, base64 image doesn't load and the loading screen stays forever.

Do you think it is possible to fix it ? 

Regards, Olivier

Here is the JS used :

`PhotoViewer.show('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAABZUlEQVR4Xu3TQREAAAiEQK9/aWvsAxMw4O06ysAommCuINgTFKQgmAEMp4UUBDOA4bSQgmAGMJwWUhDMAIbTQgqCGcBwWkhBMAMYTgspCGYAw2khBcEMYDgtpCCYAQynhRQEM4DhtJCCYAYwnBZSEMwAhtNCCoIZwHBaSEEwAxhOCykIZgDDaSEFwQxgOC2kIJgBDKeFFAQzgOG0kIJgBjCcFlIQzACG00IKghnAcFpIQTADGE4LKQhmAMNpIQXBDGA4LaQgmAEMp4UUBDOA4bSQgmAGMJwWUhDMAIbTQgqCGcBwWkhBMAMYTgspCGYAw2khBcEMYDgtpCCYAQynhRQEM4DhtJCCYAYwnBZSEMwAhtNCCoIZwHBaSEEwAxhOCykIZgDDaSEFwQxgOC2kIJgBDKeFFAQzgOG0kIJgBjCcFlIQzACG00IKghnAcFpIQTADGE4LKQhmAMNpIQXBDGA4LQQL8oTPAGUY76lBAAAAAElFTkSuQmCC')` 

Here is the logcat :

`12104:I/ActivityManager(27374): START u0 {cmp=mobile.julien.groupcamp.test/com.sarriaroman.PhotoViewer.PhotoActivity (has extras)} from uid 10139 on display 0
12110:V/ActivityManager(27374): Starting new activity ActivityRecord{248112c3 u0 mobile.julien.groupcamp.test/com.sarriaroman.PhotoViewer.PhotoActivity t481} in existing task TaskRecord{1ca13b49 #481 A=mobile.julien.groupcamp.test U=0 sz=1} from source ActivityRecord{3f410d50 u0 mobile.julien.groupcamp.test/.MainActivity t481}
12112:V/WindowManager(27374): addAppToken: AppWindowToken{177c1679 token=Token{247e9740 ActivityRecord{248112c3 u0 mobile.julien.groupcamp.test/com.sarriaroman.PhotoViewer.PhotoActivity t481}}} to stack=1 task=481 at 1
12121:D/ActivityManager(27374): resumeTopActivityLocked: Restarting ActivityRecord{248112c3 u0 mobile.julien.groupcamp.test/com.sarriaroman.PhotoViewer.PhotoActivity t481}
12131:V/ActivityThread(32060): ActivityRecord{18ee55b4 token=android.os.BinderProxy@38cf85dd {mobile.julien.groupcamp.test/com.sarriaroman.PhotoViewer.PhotoActivity}}: app=android.app.Application@ce68e7, appName=mobile.julien.groupcamp.test, pkg=mobile.julien.groupcamp.test, comp={mobile.julien.groupcamp.test/com.sarriaroman.PhotoViewer.PhotoActivity}, dir=/data/app/mobile.julien.groupcamp.test-2/base.apk
12136:V/WindowManager(27374): Adding window Window{5d8181f u0 mobile.julien.groupcamp.test/com.sarriaroman.PhotoViewer.PhotoActivity} at 5 of 12 (after Window{18a72b03 u0 mobile.julien.groupcamp.test/mobile.julien.groupcamp.test.MainActivity})
12138:I/WindowManager(27374): update systemui visibility:[8000], mLastSystemUiFlags:[8600], win:[Window{5d8181f u0 mobile.julien.groupcamp.test/com.sarriaroman.PhotoViewer.PhotoActivity}]
12165:I/WindowManager(27374): update systemui visibility:[0], mLastSystemUiFlags:[8000], win:[Window{5d8181f u0 mobile.julien.groupcamp.test/com.sarriaroman.PhotoViewer.PhotoActivity}]
12175:I/ActivityManager(27374): Displayed mobile.julien.groupcamp.test/com.sarriaroman.PhotoViewer.PhotoActivity: +135ms
12188:I/Timeline(27374): Timeline: Activity_windows_visible id: ActivityRecord{248112c3 u0 mobile.julien.groupcamp.test/com.sarriaroman.PhotoViewer.PhotoActivity t481} time:2228627234
`

**Comment by atakanyenel** [comment]
This is still a issue on android.

**Comment by JulianGarciaCastillo** [comment]
Tried a jpg base64 working perfect. Like data:image/jpeg;base64

**Comment by pengVc** [comment]
Test ok, both Android and IOS

**Comment by NareshKukreti12** [comment]
Has anyone found the solution?. Can't load base64 string to PhotoViewer.

**Comment by l3ender** [comment]
Would be nice to have this added to the readme/examples. Thanks!

**Comment by aacassandra** [comment]
iphone x, base64 not work
