### ISSUE TITLE
PhotoViewer doesn't work with large images

### ISSUE THREAD

**Issue by nagyt234** [sarriaroman/photoviewer#30]
It seems that PhotoViewer doesn't work with large images. E.g.:

```
PhotoViewer.show('http://alarp.works-organiser.com/urt/system/photos/photos/000/000/244/original/DSC00051.JPG?1452406132', 'DSC00051.JPG');
```
The files size is 7468422 Bytes, the image resolution 5152x3864.

It returns immediately with "Error loading image" on an Android Virtual Device (AVD) with 1GB RAM and Android 4.4.2. On a Samsung S4 mini also with Android 4.4.2 and 1.5 GB RAM it sometimes returns immediately sometimes "spins" forever.

An other, smaller (2 MB, 3088x3088) works but very slow (and even the orientation is ignored):
```
PhotoViewer.show('http://alarp.works-organiser.com/urt/system/photos/photos/000/000/054/original/20151014_152321.jpg?1444906627', 'DSC01165.JPG');
```

Much smaller images are working perfectly.

**Comment by sarriaroman** [comment]
Solved with version 1.1.8 #38
