### ISSUE TITLE
Stuck on loading spinner

### ISSUE THREAD

**Issue by jthk** [sarriaroman/photoviewer#32]
Hi there, 

I've followed a few posts and Ionic docs in using PhotoViewer, below is my code so far. The URL is passed okay but after tapping on the image - it will get stuck permanently with a loading spinner with no way of getting out. Any hints or clues as to why this might be happening?

Any help would be greatly appreciated.

`
import { PhotoViewer } from 'ionic-native';

@Component({
  selector: 'hero-image',
  template: `
    <div
      class="show-detail-image"
      [style.background-image]="'url(' + model.item.image + ')'"
      tappable>
      <img class="show-detail-image" [src]="model.item.image" (click)="viewFullScreenImage('url(' + model.item.image + ')', 'Detail View')"/>
      <ion-row class="hero-image-header-container">
        <ion-col>
          <h6 class="hero-image-content-header">
             {{model.item.name}}
          </h6>
        </ion-col>
      </ion-row>
    </div>
  `,
  directives: [ ProtectedDirective ]
})
export class HeroImageComponent {
  @Input() public model:Param;
  public PhotoViewer: any;

  constructor(
    private _platform: Platform
  ) {
  }

  viewFullScreenImage(image: string, title?: string): void {
    console.log('View Image in Fullscreen clicked');
    this._platform.ready()
      .then(() => {
        if (PhotoViewer)
          PhotoViewer.show(image, title);
      })
    console.log('Image', image);
  }
`

**Comment by sarriaroman** [comment]
Can you provide me the Image URL? I will try it. The problem is maybe related with the size of the image.
