### ISSUE TITLE
Problem to load images of size more than 100KB

### ISSUE THREAD

**Issue by rrraut** [sarriaroman/photoviewer#34]
Trying to open image in PhotoViewer with high dimension image & size of every image is more than 100 KB but it's not opening in PhotoViewer.

It's giving me an below error in android studio monitor,
THREAD WARNING: exec() call to PhotoViewer.show blocked the main thread for 62ms. Plugin should use CordovaInterface.getThreadPool().

**Comment by sarriaroman** [comment]
The issue about the Thread being blocked will be solved.

**Comment by sarriaroman** [comment]
Solved with version 1.1.8 #38
