### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by vernondegoede** [sarriaroman/photoviewer#36]
Is this plugin still in active development? I would love to implement it but when looking at the issues this doesn't seem to be a good idea at this point.

When can we expect some prioritising of open issues and bug fixes? :)

**Comment by sarriaroman** [comment]
The plugin is mantained and I'm working on the issues. There are no big issues, most of them are new features and the main issue mentioned about the images size on Android is normal for any kind of native app and can be workaround easily with a service to reduce the image size on demand based on the device.
