### ISSUE TITLE
Preserve Aspect Ratio

### ISSUE THREAD

**Issue by mk79** [sarriaroman/photoviewer#41]
First of all, thanks for the Plugin.

I wonder if it is possible to preserve the aspect ratio of the image - the image always stretches over the whole width and height of the screen. 

Is this possible?

Thanks.

**Comment by jlno** [comment]
+1

**Comment by sarriaroman** [comment]
Can you please tell me if Android or iOS? Thanks!

**Comment by sarinsukumar** [comment]
This commit has broken behavior. 
9f200b1d5a41be41f31eb97c42867e76d6204014

**Comment by mk79** [comment]
@sarriaroman it's on Android (Samsung Galaxy S7)

**Comment by sarriaroman** [comment]
@sarinsukumar @mk79 sadly the fix was made to avoid problems with images bigger than 100kb. Maybe a PR can be created to make it conditional but introduces the problem of the images again. I'm trying with a different library but still in testing.
Maybe works for y

**Comment by sarinsukumar** [comment]
Ok, l will probably look to fix it, will update you.





Best Regards

Sarin sukumar A

**Comment by sarinsukumar** [comment]
Is there a way I can change plugin source from the project ? will it reflect ? I tried but not reflecting the changes. I think may be we can resize the image while showing it to restrict within certain size.

**Comment by ekrapfl** [comment]
I have submitted a pull request to correct the issue.

**Comment by dawidfiruzek** [comment]
Created pull request with fix to preserve the aspect ratio of the images https://github.com/sarriaroman/photoviewer/pull/45
