### ISSUE TITLE
Reasoning for requiring external storage permissions?

### ISSUE THREAD

**Issue by vegardlarsen** [sarriaroman/photoviewer#46]
After having read the code, there seems to be no reason for requiring external storage permissions except wanting to write to the downloads folder?

Couldn't this just as easily use `getDownloadCacheDirectory` or `getDataDirectory` to get a folder that does not require these permissions? I am not an Android developer, so I don't know the specifics of what requires permission, but these seem to be safe.

**Comment by WuglyakBolgoink** [comment]
@vegardlarsen  WRITE_EXTERNAL_STORAGE

**Comment by vegardlarsen** [comment]
@WuglyakBolgoink I'm not sure what you mean by that. The point of a photo viewer should not be to write stuff to **external** storage, but to actually display the photo. It should not need access to external storage for that.

**Comment by sarriaroman** [comment]
When the code was made for some reason on some versions sharing feature was failing so the workaround was to create a file and share from the file. That is why the permission is requested.

**Comment by vegardlarsen** [comment]
Would it be better if you only required that permission if the sharing feature actually failed? Or disabling that feature so this would no longer be an issue?

I am very hesitant to ask my users for external storage permissions without having any real reason for doing so.

**Comment by sarriaroman** [comment]
The sharing of the plugin must be rewrite to avoid asking for External Storage permission because is not required anymore. If you feel ok making that change you can do it and create a PR and I will be happy to merge it.

**Comment by vegardlarsen** [comment]
I'm afraid I am not enough of an Android developer to do this easily. I would love if someone would pick this up and do it. :)

**Comment by JulianGarciaCastillo** [comment]
When is this change going to be released via npm?
