### ISSUE TITLE
Android does not work with cordova file plugin

### ISSUE THREAD

**Issue by Hirbod** [sarriaroman/photoviewer#6]
When I use the file-uri resource from cordova file plugin, the image will not load. It works fine on iOS, but not on android. Path is something like this:

content://media/external/images/media/...

```js
            navigator.camera.getPicture(function( imgdata ) 
            {

                //console.log(imgdata);
                
                if (imgdata.substring(0,21)=="content://com.android") {
                    photo_split=imgdata.split("%3A");
                    imgdata = "content://media/external/images/media/"+photo_split[1];
                }
```

Src of my image is "imagedata", which works perfectly fine. But sadly it does not show in the PhotoViewer. Seems like iOS UIDocumentationController will automatically handle internal urls

**Comment by sarriaroman** [comment]
Needs some testing but is implemented.

**Comment by Hirbod** [comment]
Confirmed! Works perfectly! You are great Roman!
