### ISSUE TITLE
iOS 10 constant spinning wheel on image load

### ISSUE THREAD

**Issue by Jacbey** [sarriaroman/photoviewer#82]
Whenever I try to invoke the function I get a spinning wheel.  I have tried with multiple images, script and image locations and whenever the image is located on the device I am unable to open it.

No error is produced in console, **or anywhere else for that matter.**  I don't know if a permissions request is required but other people seem to think so.

This seems as it is a common problem for a lot of people and has so far been ignored and it would be really appreciated if this can be fixed.

**Comment by RezaRahmati** [comment]
Same here, on device and simulator tries to load and then app crashes with no error

**Comment by MT--** [comment]
Are you using WKWebView? (I have not been able to get this plugin to work with WKWebView at all, even after successfully loading local assets into `<img>` tags, etc...

**Comment by RezaRahmati** [comment]
@MT-- Thanks for answer, finally I switched to [https://github.com/Riron/ionic-img-viewer](https://github.com/Riron/ionic-img-viewer)

**Comment by MT--** [comment]
@RezaRahmati @Jacbey, I got this to work by using the File plugin:

`this.file.readAsDataURL(cordova.file.applicationDirectory + 'www/assets/img/img.jpg')
  .then(dataURL => this.photoViewer.show(dataURL));`

I have not tested on Android, just FYI.

**Comment by Jacbey** [comment]
@MT-- Thanks for the idea.  I actually switched to this plugin: https://github.com/keensoft/FullScreenImage-Cordova-Plugin  because it's blatantly clear that although sarriaroman is active on Github, he doesn't give a damn about this plugin or the state it is in.

**Comment by jimmypewtress** [comment]
I tried adding `file://` to the front of the path used to display the image in the `<img>` tags etc and it seems to work ok, i.e.

`photoViewer("file://" + this.cordovaDataDirectory + fileName, title, {share: false});`
