### ISSUE TITLE
iOS: Title won't reset

### ISSUE THREAD

**Issue by Hirbod** [sarriaroman/photoviewer#9]
Hi @sarriaroman,

when I open an image on iOS with a title, and the next time, I open one without a title, it will show the last title (I guess you need to reset some var on re-open)

**Comment by Hirbod** [comment]
Oh, no, it just wont accept anything else. Once a title was provided, it will always show the first, initied title

**Comment by sarriaroman** [comment]
Solved in 1.1.2
